[workspace]
members = [
    "crates/soulbase-types",
    "crates/soulbase-errors",
    "crates/soulbase-config",
    "crates/soulbase-auth",
    "crates/soulbase-interceptors",
    "crates/soulbase-sandbox",
    "crates/soulbase-llm",
    "crates/soulbase-tools",
    "crates/soulbase-storage",
    "crates/soulbase-tx",
    "crates/soulbase-observe",
    "crates/soulbase-cache",
    "crates/soulbase-blob",
    "crates/soulbase-crypto",
    "crates/soulbase-net",
    "crates/soulbase-infra"
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
