[package]
name = "soulbase-tools"
version = "1.0.0"
edition = "2021"
license = "Apache-2.0"
description = "Tool SDK / Manifest / Registry / Invocation Protocol for the Soul platform"
repository = "https://github.com/RcityHunter/soul-base"

[features]
default = ["schema_json"]
schema_json = ["schemars", "jsonschema"]
tenant_scoped_registry = []
idempotency_store_redis = []

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
schemars = { version = "0.8", optional = true }
jsonschema = { version = "0.17", optional = true }
async-trait = "0.1"
thiserror = "1"
parking_lot = "0.12"
ahash = "0.8"
chrono = "0.4"

soulbase-types = { path = "../soulbase-types", version = "1.0.0" }
soulbase-errors = { path = "../soulbase-errors", version = "1.0.0" }
soulbase-auth = { path = "../soulbase-auth", version = "1.0.0" }
soulbase-sandbox = { path = "../soulbase-sandbox", version = "1.0.0" }

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tempfile = "3"
