[package]
name = "soulbase-types"
version = "1.0.0"
edition = "2025"
rust-version = "1.78"
license = "Apache-2.0"
description = "Data contract primitives for the Soul platform (IDs, Subject, Scope, Consent, Envelope...)."
repository = "https://github.com/RcityHunter/soul-base"
homepage = "https://github.com/RcityHunter/soul-base"
documentation = "https://github.com/RcityHunter/soul-base/tree/main/crates/soulbase-types"

[features]
schema = ["schemars"]
serde_borrow = []
uuid = ["dep:uuid"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
semver = "1"
schemars = { version = "0.8", optional = true }
uuid = { version = "1", optional = true, features = ["v4"] }
nanoid = "0.4"

[dev-dependencies]
serde_json = "1"

[package.metadata]
release_year = 2025
