[package]
name = "soulbase-cache"
version = "1.0.0"
edition.workspace = true
license.workspace = true

[features]
default = []
redis = ["dep:redis"]
observe = ["soulbase-observe"]

[dependencies]
redis = { version = "0.25", optional = true, default-features = false, features = ["tokio-comp", "connection-manager"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
async-trait = "0.1"
thiserror = "1"
parking_lot = "0.12"
lru = "0.12"
once_cell = "1"
bytes = "1"
chrono = "0.4"
tokio = { version = "1", features = ["rt", "sync", "time", "macros"] }
rand = { version = "0.8", features = ["std"] }
tracing = "0.1"

soulbase-errors = { path = "../soulbase-errors", version = "1.0.0" }
soulbase-observe = { path = "../soulbase-observe", version = "1.0.0", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
serde_json = "1"
mini-redis = "0.4"
